BodSpeak/config/routes.rb
BodSpeakJisha::Application.routes.draw do
  resources :messages

  resources :users

  get "static_pages/home"
  resources :sessions, only: [:new, :create, :destroy]
  root :to => 'static_pages#home'
  match '/signin',  to: 'users#show',         via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/users',    to: 'users#index',        via:'get'

end

BodSpeak/app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user
end

BodSpeak/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :firstname, :lastname, :password_digest, :user_type
  has_many :messages   ,  dependent:   :destroy

  before_save { self.email = email.downcase }
  validates :firstname, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  #validates :password, length: { minimum: 6 }
end

BodSpeak/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

BodSpeak/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end
end

BodSpeak/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create

  end
end

BodSpeak/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

BodSpeak/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

BodSpeak/app/helpers/application_helper.rb
module ApplicationHelper
end

BodSpeak/app/helpers/messages_helper.rb
module MessagesHelper
end

BodSpeak/app/helpers/sessions_helper.rb
module SessionsHelper
end

BodSpeak/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

BodSpeak/app/helpers/users_helper.rb
module UsersHelper
end

BodSpeak/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BodSpeakJisha</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

BodSpeak/app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>

    <div class="field">
      <%= f.label :user_id %><br />
      <%= f.text_field :user_id %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

BodSpeak/app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

BodSpeak/app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.content %></td>
    <td><%= message.user_id %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

BodSpeak/app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

BodSpeak/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @message.content %>
</p>

<p>
  <b>User:</b>
  <%= @message.user_id %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

BodSpeak/app/views/static_pages/home.html.erb
<h1>Welcome to BodSpeak</h1>
<p1>"                                         About BodSpeak"</p1>
<h1>Sign in</h1>

<div class="container">
<div class="row">
  <div class="span6 offset5">
    <%= form_for(:session, url: sessions_path) do |f| %>

        <%= f.label :email %>
        <div class="column">
                  </div>
        <%= f.text_field :email %>
        </div>
        </div>

        <%= f.label :password %>
        <div class="column">
        </div>
        <%= f.password_field :password %>
        <%= link_to "Sign in", users_path %>


    <% end %>


    <p>New user? <%= link_to "Sign up", signup_path %></p>
    </div>

BodSpeak/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
    <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

BodSpeak/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

BodSpeak/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>


    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.firstname %></td>
    <td><%= user.lastname %></td>
    <td><%= user.email %></td>


    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

BodSpeak/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

BodSpeak/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p> Welcome <%= @user.firstname %> </p>

<p>
  <b>First name:</b>
  <%= @user.firstname %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.lastname %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<p>
  <b>Messages:</b>
  <div class="row"></div>

  <% @user.messages.each do |message| %>
    <%= link_to message.content[0..25], message %><br/>
  <p> Posted <%= time_ago_in_words message.created_at %> ago  </p>
    <br/>
  <% end %>
  <%= link_to "Create new message", new_message_path( :user_id =>@user.id) %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>